cada:
	cabal configure
	cabal build
	cabal run
	cp api.js ../ide/atom/language-cada/lib/

test:
	cabal test

bench:
	cabal bench --benchmark-option=--output --benchmark-option=bench.html

clean:
	cabal clean
